config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users 
  
  resource :session, only: [:new, :create, :destroy]
  
  resources :goals
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  details    :text
#  private?   :boolean          default(FALSE), not null
#  completed? :boolean          default(FALSE), not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ApplicationRecord
  validates :title, :user_id, presence: true 
  
  belongs_to :user
    # foreign_key: :user_id,
    # class_name: :User
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :email, :password_digest, :session_token, presence: true 
  validates :username, :email, :password_digest, :session_token, uniqueness: true 
  # validates :password, length: {minimum: 6, allow_nil: true}
  
  has_many :goals, dependent: :destroy
  
  after_initialize :ensure_session_token
  attr_reader :password
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  private
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def login!(user)
    session[:session_token] = user.reset_session_token!
  end 
  
  # def logout!
  #   session[:session_token] = nil 
  #   user.reset_session_token
  # end 
  
  def current_user 
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end 
  
  def logged_in? 
    !current_user.nil?
  end   
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  
  def new
    @goal = Goal.new
    render :new
  end
  
  def create
    debugger
    params[:goal][:private?] = params[:goal][:private?].nil? ? true : false
    params[:goal][:completed?] = params[:goal][:completed?].nil? ? true : false
    params[:goal][:user_id] = current_user.id 
    # byebug
    @goal = Goal.new(goal_params)
    @user = current_user
    # byebug
    if @goal.save! 
      redirect_to user_url(@user)
    else 
      flash[:errors] = @goal.errors.full_messages
      render :new
    end 
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def show
    
  end
  
  def destroy
    
  end
  
  def goal_params 
    params.require(:goal).permit(:title, :details, :private?, :completed?, :user_id)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new 
    user = User.new 
    render :new
  end 
  
  
  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ['Invalid username or password or email']
      render :new
    end
  end
  
  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new 
    @user = User.new 
    render :new
  end 
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action=" <%= goals_url %>" method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
  
  <label for="title">Title:<input type="text" name="goal[title]" value=""></label>
  <label for="details">Details:<textarea name="goal[details]"></textarea></label> 
  <label for="private?">Private? <input type="checkbox" name="goal[private?]" value="true"> </label>
  <label for="completed?">Completed? <input type="checkbox" name="goal[completed?]" value="true"> </label>
  <input type="submit" name="" value="Create goal">
  
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DreamApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New user signup</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
  <label for="username">Username: <input type="text" name="user[username]" value=""></label>
  <label for="email">Email: <input type="text" name="user[email]" value=""></label>
  <label for="password">Password: <input type="password" name="user[password]" value=""></label>
  <input type="submit" value="Sign Up!">
</form>

app/views/users/show.html.erb
<h1>Hello <%= @user.username %></h1>
<br>
<form action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Log Out">
  
</form>